## Criação de Matrizes

In [1]:
"""
Para criar uma matriz básica, basta usar a função do NumPy
como faria com um vetor, mas você define dimensões adicionais. 
Uma dimensão é uma direção na matriz. Por exemplo, uma matriz 
bidimensional contém linhas(uma direção) e colunas(uma segunda direção)
"""
import numpy as np
matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
"""
Para acessar um determinado elemento de matriz, você fornece um valor
de índice de linha e coluna
"""
matrix[0,0]

1

In [0]:
"""
Você pode produzir matrizes com qualquer número de dimensões 
usando uma técnica semelhante.  
"""
matrix = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
matrix

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [0]:
"""
Neste caso, você deve fornecer um valor de índice x, y e z para 
acessar um determinado valor. Por exemplo, matrix[0, 1, 1] acessa 
o valor 4.
"""
matrix[0, 1, 1]

4

In [0]:
"""
Produz uma matriz contendo quatro linhas e quatro colunas 
preenchidas com valores int32
"""
matrix = np.ones ([4,4], dtype=np.int32)
matrix

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [0]:
"""
Criará uma matriz tridimensional. Desta vez, a matriz conterá
valores booleanos true. 
https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html
"""
matrix = np.ones ([4,4,4], dtype=np.bool)
matrix

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [3]:
"""
Tudo o que você realmente precisa saber é como criar uma matriz.
O método mais fácil é fazer uma chamada semelhante à que você usa
para a função array, mas usando a função .mat() em vez disso
"""
matrix = np.mat([[1,2,3], [4,5,6], [7,8,9]])
matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
"""
Você também pode converter um array existente em uma matriz usando 
a função asmatrix(). Use a função asarray() para converter uma matriz 
de volta a um array.
"""
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9])
matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(np.asmatrix(array)) # de array para matriz
print("************************************")
print(np.asarray(matrix)) # de matriz para array

[[1 2 3 4 5 6 7 8 9]]
************************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
"""
Dois métodos comuns de multiplicação de uma matriz são 
"elemento por elemento" e "produto matricial". A abordagem 
elemento por elemento é simples. O código a seguir produz uma 
multiplicação elemento por elemento de duas matrizes:
https://docs.scipy.org/doc/numpy/reference/routines.linalg.html.
"""
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2,3],[4,5,6]]) 
print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [6]:
"""
Ao executar um produto matricial com uma matriz, o número de colunas 
na matriz a deve corresponder ao número de linhas na matriz b. 
No entanto, o número de linhas na matriz a pode ser qualquer número, 
e o número de colunas na matriz b pode ser qualquer número, desde que 
você crie de produto matricial de a por b
"""
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2,3],[3,4,5],[5,6,7]]) 
print(a.dot(b))

[[22 28 34]
 [49 64 79]]


In [7]:
"""
Uma vantagem de usar a classe matriz numpy é que algumas tarefas se 
tornam mais simples. Por exemplo, a multiplicação funciona 
precisamente como você espera. O código a seguir produz um produto 
matricial usando a classe matriz:
"""
a = np.mat([[1,2,3],[4,5,6]]) 
b = np.mat([[1,2,3],[3,4,5],[5,6,7]]) 
print(a*b)

[[22 28 34]
 [49 64 79]]


In [8]:
print("****************************")
remodelar = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) 
print(remodelar)
print("****************************")
print(np.transpose(remodelar))

****************************
[[1 2 3 4]
 [5 6 7 8]]
****************************
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [9]:
"""
O método mais fácil é fazer uma chamada semelhante à que você usa 
para a função array, mas usando a função .mat() em vez disso
"""
matrix = np.mat([[1,2,3], [4,5,6], [7,8,9]])
matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Multiplicação de Matrizes
O código a seguir produz uma multiplicação elemento por elemento de duas matrizes:

In [10]:
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2,3],[4,5,6]]) 
print(a*b)

[[ 1  4  9]
 [16 25 36]]


Infelizmente, uma multiplicação elemento por elemento pode produzir resultados incorretos ao trabalhar com algoritmos. Em muitos casos, o que você realmente precisa é de um produto matricial, que é a soma dos produtos de duas sequências numéricas. Você pode aprender mais sobre as funções lineares de manipulação de álgebra para numpy na documentação oficial, link abaixo https://docs.scipy.org/doc/numpy/reference/routines.linalg.html.<br><br>
Ao executar um produto matricial com uma matriz, o número de colunas na matriz a deve corresponder ao número de linhas na matriz b. No entanto, o número de linhas na matriz a pode ser qualquer número, e o número de colunas na matriz b pode ser qualquer número, desde que você crie de produto matricial de a por b. Por exemplo, o código a seguir produz um produto .dot() correto:


In [11]:
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2,3],[3,4,5],[5,6,7]]) 
print(a.dot(b))

[[22 28 34]
 [49 64 79]]


In [12]:
"""
Uma vantagem de usar a classe matriz numpy é que algumas tarefas 
se tornam mais simples. Por exemplo, a multiplicação funciona 
precisamente como você espera. O código a seguir produz um produto 
matricial usando a classe matriz:
"""
a = np.mat([[1,2,3],[4,5,6]]) 
b = np.mat([[1,2,3],[3,4,5],[5,6,7]]) 
print(a*b)

[[22 28 34]
 [49 64 79]]


## Operações Matriciais Avançadas

In [0]:
# RESHAPE
"""
Felizmente, numpy vem com uma função especial de remodelar, 
o reshape, que permite colocar os dados em qualquer forma necessária.
Na verdade, você pode usá-la para remodelar um vetor em uma matriz, 
como mostramos no código a seguir:
"""
remodelar = np.array([1,2,3,4,5,6,7,8])
print(remodelar)
print("*************************")
print("Remodelamos para 2linhas/4colunas")
print(remodelar.reshape(2,4))
print("*************************")
print("Remodelamos x,y,z recebendo 2")
print(remodelar.reshape(2,2,2))

[1 2 3 4 5 6 7 8]
*************************
Remodelamos para 2linhas/4colunas
[[1 2 3 4]
 [5 6 7 8]]
*************************
Remodelamos x,y,z recebendo 2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [0]:
"""
Você deve fornecer uma forma que se encaixe com o número 
necessário de elementos. Por exemplo, chamar
remodelar.reshape(2,3,2) vai dar errado porque não há 
elementos suficientes para fornecer uma matriz desse tamanho.
"""
remodelar.reshape(2,3,2)

ValueError: ignored

## Matriz Transposta
A transposição ocorre quando uma matriz de forma *nxm* é transformada em uma matriz *mxn* trocando as linhas com as colunas.

In [0]:
remodelar = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) 
print(np.transpose(remodelar))

## Matriz Inversa
Como a maioria dos números escalares (exceções incluem zero) tem um número cuja multiplicação resulta em um valor de 1, a ideia é encontrar um inverso matricial cuja multiplicação resultará em uma matriz especial chamada matriz de identidade.

In [0]:
print(np.identity(4))

In [0]:
"""
O inverso de uma matriz A é indicado como A-1. 
Com numpy, você usa a função linalg.inv para criar um inverso.
O exemplo a seguir mostra como criar um inverso, usamos ele para obter 
um produto matricial com .dot() e, em seguida, comparar esse produto 
matricial com a matriz de identidade usando a função allclose():
"""
a = np.array([[1,2], [3,4]]) 
b = np.linalg.inv(a) 
print(np.allclose(np.dot(a,b), 
np.identity(2)))

## Tensores

In [0]:
# REDE NEURAL SIMPLISTA EM 4 LINHAS DE CÓDIGO
inputs = np.array([5, 10, 15])
pesos = np.array([[.5,.2,-1], [.3,.4,.1], [-.2,.1,.3]])
resultado = np.dot(inputs, pesos)
resultado

array([2.5, 6.5, 0.5])

## Vetorização

In [0]:
def Soma(a, b):
  return a + b 
Vetorizar = np.vectorize(Soma) 
print(Vetorizar([1, 2, 3, 4], [1, 2, 3, 4]))

[2 4 6 8]
