# Pré-processamento de dados

In [21]:
import pandas as pd
from IPython.display import Image


In [46]:
base = pd.read_csv('data/credit_data.csv')

In [47]:
base.head()

clientid        income        age         loan  default
0         1  66155.925095  59.017015  8106.532131        0
1         2  34415.153966  48.117153  6564.745018        0
2         3  57317.170063  63.108049  8020.953296        0
3         4  42709.534201  45.751972  6103.642260        0
4         5  66952.688845  18.584336  8770.099235        1

In [48]:
base.describe()

clientid        income          age          loan      default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

In [49]:
base.loc[base['age'] < 0]

clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0

In [50]:
# apagar a coluna
#base.drop('age', 1, inplace=True)

In [51]:
# apagar somente os registros com problema
#base.drop(base[base.age < 0].index, inplace=True)

In [52]:
# preencher os valores manualmente
# preencher os valores com a média
base.mean()
base['age'].mean()
base['age'][base.age > 0].mean()
base.loc[base.age < 0, 'age'] = 40.92

In [53]:
pd.isnull(base['age'])
base.loc[pd.isnull(base['age'])]

previsores = base.iloc[:, 1:4].values
classe = base.iloc[:, 4].values

In [54]:
base.loc[base.age.isna(),'age'] = 40.92

## Padrinização e normalização

Padrinização: $$X=\frac{x-média(x)}{std(x)}$$

Normalização:  $$X=\frac{x-min(x)}{max(x)-min(x)}$$

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

In [18]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(previsores,classe,test_size=0.25,random_state=0)

# Algoritimo Naive Bayes

## Teorema de Bayes

Teorema de Bayes : <p> $$P(A/B)=\frac{P(B/A)P(A)}{P(B)}$$

## o Algortitimo Gera uma tabela de probabilidades

<img src="imagens/Algoritimo_naive_bayes_aprende.png" />

## entao após gerar a tabela, ele usa calculo de probabilidades para classificar

<img src="imagens/Algoritimo_naive_bayes_classifica.png" />

## Correcação Laplaciana

### Caso o calculo das probabildiades retorne 0 entao usamos correção laplaciana, que adicionara um registro adicional (ele adiciona quantos registros for nescessario, para que nao ocorra a divisão por zero)

## Naive bayes (radius)

<img src='imagens/moreconcepts_naive_bayes.png'/>

## Vantagens X Desvantagens

<h2>Vantagens</h2>
<OL>
<LI>Rapido</LI>
<LI>Simplicidade de interpretação</LI>
<LI>trabalha com altas dimensões</LI>
<LI>Boas Previsoes em Bases Pequenas</LI>
</OL>
<h2>Desvantagens</h2>
<OL>
<LI>Combinação de Caracteristicas (atributos independentes) - cada par de caracteristicas são idependentes </LI>
<h6>EX: Tratar renda e Divida como atrabutos diferentes</h6>
</OL>

## Naive bayes com Scikit-learn base (risco_de_credito)

In [65]:
base = pd.read_csv('data/risco_de_credito.csv')

In [66]:
base.head()

historia divida garantias     renda     risco
0          ruim   alta   nenhuma      0_15      alto
1  desconhecida   alta   nenhuma     15_35      alto
2  desconhecida  baixa   nenhuma     15_35  moderado
3  desconhecida  baixa   nenhuma  acima_35      alto
4  desconhecida  baixa   nenhuma  acima_35     baixo

In [79]:
previsores = base.iloc[:,0:4].values
classe = base.iloc[:,4].values

In [80]:
from sklearn.preprocessing import LabelEncoder

In [81]:
labelencoder = LabelEncoder()
previsores[:,0] = labelencoder.fit_transform(previsores[:,0])
previsores[:,1] = labelencoder.fit_transform(previsores[:,1])
previsores[:,2] = labelencoder.fit_transform(previsores[:,2])
previsores[:,3] = labelencoder.fit_transform(previsores[:,3])

In [82]:
from sklearn.naive_bayes import GaussianNB

In [83]:
classificador = GaussianNB()


In [84]:
classificador.fit(previsores,classe)

GaussianNB(priors=None, var_smoothing=1e-09)

In [101]:
classificador.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [102]:
classificador.class_count_

array([6., 5., 3.])

In [103]:
classificador.class_prior_

array([0.42857143, 0.35714286, 0.21428571])

In [99]:
resultado = classificador.predict([[0,0,1,2],[3,0,0,0]])

In [100]:
resultado

array(['baixo', 'moderado'], dtype='<U8')

## Naive bayes com Scikit-learn base (credit_data)

In [124]:
base = pd.read_csv('data/credit_data.csv')

In [125]:
media_idade =base['age'].mean()
base.loc[base.age < 0, 'age'] = media_idade

In [126]:
previsores = base.iloc[:, 1:4].values
classe = base.iloc[:, 4].values

In [130]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [132]:
imputer = imputer.fit(previsores[:,1:4])
previsores[:,1:4] = imputer.transform(previsores[:,1:4])

In [133]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

In [134]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(previsores,classe,test_size=0.25,random_state=0)

In [135]:
from sklearn.naive_bayes import GaussianNB
classificador = GaussianNB()

In [136]:
classificador.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [137]:
previsoes = classificador.predict(X_test)

In [140]:
pd.DataFrame(data=[previsoes,y_test])

0    1    2    3    4    5    6    7    8    9    ...  490  491  492  493  \
0    1    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    1    0    0    0    0    0    0    0    0    0  ...    1    0    0    0   

   494  495  496  497  498  499  
0    0    0    0    0    0    0  
1    0    0    0    0    1    1  

[2 rows x 500 columns]

In [141]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [149]:
precisao = accuracy_score(y_test,previsoes)
precisao

0.938

In [148]:
matriz = confusion_matrix(y_test,previsoes)
matriz

array([[428,   8],
       [ 23,  41]])

# Arvores de Decisao

<object width="400" height="500" type="application/pdf" data="/pdf/aprendizagem_bayseana.pdf">
    <p>Insert your error message here, if the PDF cannot be displayed.</p>
</object>

In [1]:
'pdf/aprendizagem_bayseana.pdf'

'pdf/aprendizagem_bayseana.pdf'